export const PDF_PALETTE = {
    TEAL:   [8,   145, 178],
    RED:    [220,  38,  38],
    DARK:   [30,   41,  59],
    GREY:   [100, 116, 139],
    LGREY:  [226, 232, 240],
    LGREY2: [241, 245, 249],
    LGREY3: [248, 250, 252],
    RED_BG: [254, 242, 242],
    WHITE:  [255, 255, 255],
};

export const PARAMETROS = {
    superficiecorporal:  { label: 'Superficie Corporal',    unit: 'm²'            },
    imc:                 { label: 'IMC',                    unit: 'kg/m²'         },
    vpercent:            { label: 'V%',                     unit: '%'             },
    schwartz_neo:        { label: 'eGFR-Smeets',            unit: 'ml/min/1.73m²' },
    schwartz_lact:       { label: 'eGFR Schwartz lactante', unit: 'ml/min/1.73m²' },
    schwartz_bedside:    { label: 'eGFR Schwartz Bedside',  unit: 'ml/min/1.73m²' },
    bokenkamp:           { label: 'eGFR Bökenkamp',        unit: 'ml/min/1.73m²' },
    ckid_u25_cr:         { label: 'eGFR CKiD U25 Cr',       unit: 'ml/min/1.73m²' },
    ekfc_cr:             { label: 'eGFR EKFC Cr',           unit: 'ml/min/1.73m²' },
    ckid_u25_cistc:      { label: 'eGFR CKiD U25 CistC',   unit: 'ml/min/1.73m²' },
    ekfc_cistc:          { label: 'eGFR EKFC CystC',        unit: 'ml/min/1.73m²' },
    ckid_u25_combinado:  { label: 'eGFR Combinado',         unit: 'ml/min/1.73m²' },
    efna:                { label: 'EF Na',                  unit: ''             },
    efau:                { label: 'EF AU',                  unit: ''             },
    efk:                 { label: 'EF K',                   unit: ''             },
    efcl:                { label: 'EF Cl',                  unit: ''             },
    cacr:                { label: 'Ca/Cr',                  unit: 'mg/mg'         },
    mgcr:                { label: 'Mg/Cr',                  unit: 'mg/mg'         },
    pcr:                 { label: 'P/Cr',                   unit: 'mg/mg'         },
    rtp:                 { label: 'RTP',                    unit: '%'             },
    aucr:                { label: 'AU/Cr',                  unit: 'mg/mg'         },
    oxalatocr:           { label: 'Oxalato/Cr',             unit: 'mg/mg'         },
    albcr:               { label: 'Alb/Cr',                 unit: 'mg/g'          },
    protcr:              { label: 'Prot/Cr',                unit: 'mg/g'          },
    citratocr:           { label: 'Citrato/Cr',             unit: 'mg/mg'         },
    cacitrato:           { label: 'Ca/Citrato',             unit: ''              },
    nak:                 { label: 'Na/K orina',             unit: ''              },
    uricosuria:          { label: 'Uricosuria',             unit: 'mg/1.73m²/día' },
    calciuria:           { label: 'Calciuria',              unit: 'mg/kg/día'     },
    citraturia:          { label: 'Citraturia',             unit: 'mg/kg/día'     },
    fosfaturia:          { label: 'Fosfaturia',             unit: 'mg/kg/día'     },
    oxaluria:            { label: 'Oxaluria',               unit: 'mg/1.73m²/día' },
    magnesuria:          { label: 'Magnesuria',             unit: 'mg/kg/día'     },
    albuminuria:         { label: 'Albuminuria',            unit: 'mg/1.73m²/día' },
    proteinuria:         { label: 'Proteinuria',            unit: 'mg/m²/día'     },
    proteinuriaestimada: { label: 'Proteinuria estimada',   unit: 'mg/m²/día'     },
    
    // Datos Crudos (Para el reporte unificado)
    urea_mg_dl:             { label: 'Urea',                    unit: 'mg/dL' },
    creatinina_enz_mg_dl:   { label: 'Cr',                      unit: 'mg/dL' },
    cistatina_c_mg_l:       { label: 'Cistatina C',             unit: 'mg/L' },
    na_plasma_meq_l:        { label: 'Na',                      unit: 'mEq/L' },
    k_plasma_meq_l:         { label: 'K',                       unit: 'mEq/L' },
    cl_plasma_meq_l:        { label: 'Cl',                      unit: 'mEq/L' },
    au_plasma_mg_dl:        { label: 'AU',                      unit: 'mg/dL' },
    ca_plasma_mg_dl:        { label: 'Ca',                      unit: 'mg/dL' },
    p_plasma_mg_dl:         { label: 'P',                       unit: 'mg/dL' },
    mg_plasma_mg_dl:        { label: 'Mg',                      unit: 'mg/dL' },
    pth_pg_ml:              { label: 'PTH',                     unit: 'pg/mL' },
    vitamina_d_ng_ml:       { label: 'Vitamina D',              unit: 'ng/mL' },
    fosfatasa_alcalina_u_l: { label: 'Fosfatasa alcalina',      unit: 'U/L' },
    hb_g_l:                 { label: 'Hemoglobina',             unit: 'g/L' },
    ferritina_ng_ml:        { label: 'Ferritina',               unit: 'ng/mL' },
    ist_percent:            { label: 'IST',                     unit: '%' },
    ph_plasma:              { label: 'pH',                      unit: '' },
    pco2_mmhg:              { label: 'pCO2',                    unit: 'mmHg' },
    hco3_mmol_l:            { label: 'HCO3',                    unit: 'mmol/L' },
    exceso_bases_mmol_l:    { label: 'Exceso de bases',         unit: 'mmol/L' },
    densidad:               { label: 'Densidad',                unit: '' },
    ph_orina:               { label: 'pH',                      unit: '' },
    osmolalidad_orina_mosm_kg: { label: 'Osmolalidad urinaria', unit: 'mOsm/kg' }
};

export const SECCIONES = [
    { titulo: 'Datos Generales', keys: ['superficiecorporal','imc'] },
    { titulo: 'Hidrosalino', keys: ['urea_mg_dl','creatinina_enz_mg_dl','schwartz_neo','schwartz_lact','schwartz_bedside','ckid_u25_cr','ekfc_cr','cistatina_c_mg_l','bokenkamp','ckid_u25_cistc','ekfc_cistc','ckid_u25_combinado','vpercent','na_plasma_meq_l','efna','k_plasma_meq_l','efk','cl_plasma_meq_l','efcl','au_plasma_mg_dl','efau'] },
    { titulo: 'Metabolismo fosfocálcico', keys: ['ca_plasma_mg_dl','cacr','p_plasma_mg_dl','rtp','mg_plasma_mg_dl','mgcr','pcr','pth_pg_ml','vitamina_d_ng_ml','fosfatasa_alcalina_u_l'] },
    { titulo: 'Hematológico', keys: ['hb_g_l','ferritina_ng_ml','ist_percent'] },
    { titulo: 'Gasometría', keys: ['ph_plasma','pco2_mmhg','hco3_mmol_l','exceso_bases_mmol_l'] },
    { titulo: 'Orina puntual', keys: ['densidad','ph_orina','protcr','proteinuriaestimada','albcr','osmolalidad_orina_mosm_kg','aucr','nak','cacr','citratocr','cacitrato','oxalatocr'] },
    { titulo: 'Orina de 24h', keys: ['uricosuria','calciuria','citraturia','fosfaturia','magnesuria','oxaluria','albuminuria','proteinuria'] }
];

export const TAB_FIELDS = {
    'datos-basicos-tab':  ['fechanacimiento', 'fechaanalitica', 'pesokg', 'tallacm'],
    'bioquimica-tab':     ['ureamgdl', 'creatininaenzmgdl', 'auplasmamgdl', 'naplasmameql',
                           'kplasmameql', 'clplasmameql', 'fosfatasaalcalinaul', 'caplasmamgdl',
                           'pplasmamgdl', 'mgplasmamgdl', 'pthpgml', 'vitaminadngml', 'cistatinacmgl'],
    'gasometria-tab':     ['phplasma', 'pco2mmhg', 'hco3mmoll', 'excesobasesmmoll'],
    'orina-puntual-tab':  ['densidad', 'phorina', 'auorinamgdl', 'naorinameql', 'korinameql',
                           'clorinameql', 'osmolalidadorinamosmkg', 'caorinamgdl', 'fosforoorinamgdl',
                           'magnesioorinamgdl', 'albuminaorinamgdl', 'creatininaorinamgdl',
                           'proteinasorinamgdl', 'citratoorinamgdl', 'oxalatoorinamgdl'],
    'hematologia-tab':    ['hbgl', 'ferritinangml', 'istpercent'],
    'orina-24h-tab':      ['au24hmg', 'ca24hmg', 'p24hmg', 'mg24hmg', 'albumina24hmg',
                           'proteinas24hmg', 'citrato24hmg', 'oxalato24hmg'],
    'ecografia-tab':      ['rinonizquierdomm', 'rinonderechomm']
};