export const PDF_PALETTE = {
    TEAL:   [8,   145, 178],
    RED:    [220,  38,  38],
    DARK:   [30,   41,  59],
    GREY:   [100, 116, 139],
    LGREY:  [226, 232, 240],
    LGREY2: [241, 245, 249],
    LGREY3: [248, 250, 252],
    RED_BG: [254, 242, 242],
    WHITE:  [255, 255, 255],
};

export const PARAMETROS = {
    superficiecorporal:  { label: 'Superficie Corporal',    unit: 'm²'            },
    imc:                 { label: 'IMC',                    unit: 'kg/m²'         },
    vpercent:            { label: 'V%',                     unit: '%'             },
    schwartz_neo:        { label: 'eGFR Schwartz neonatal', unit: 'ml/min/1.73m²' },
    schwartz_lact:       { label: 'eGFR Schwartz lactante', unit: 'ml/min/1.73m²' },
    schwartz_bedside:    { label: 'eGFR Schwartz Bedside',  unit: 'ml/min/1.73m²' },
    bokenkamp:           { label: 'eGFR Böckenkamp',        unit: 'ml/min/1.73m²' },
    ckid_u25_cr:         { label: 'eGFR CKiD U25 Cr',       unit: 'ml/min/1.73m²' },
    ekfc_cr:             { label: 'eGFR EKFC Cr',           unit: 'ml/min/1.73m²' },
    ckid_u25_cistc:      { label: 'eGFR CKiD U25 CistC',   unit: 'ml/min/1.73m²' },
    ekfc_cistc:          { label: 'eGFR EKFC CystC',        unit: 'ml/min/1.73m²' },
    ckid_u25_combinado:  { label: 'eGFR Combinado',         unit: 'ml/min/1.73m²' },
    efna:                { label: 'EF Na',                  unit: ''             },
    efau:                { label: 'EF AU',                  unit: ''             },
    efk:                 { label: 'EF K',                   unit: ''             },
    efcl:                { label: 'EF Cl',                  unit: ''             },
    cacr:                { label: 'Ca/Cr',                  unit: 'mg/mg'         },
    mgcr:                { label: 'Mg/Cr',                  unit: 'mg/mg'         },
    pcr:                 { label: 'P/Cr',                   unit: 'mg/mg'         },
    rtp:                 { label: 'RTP',                    unit: '%'             },
    aucr:                { label: 'AU/Cr',                  unit: 'mg/mg'         },
    oxalatocr:           { label: 'Oxalato/Cr',             unit: 'mg/mg'         },
    albcr:               { label: 'Alb/Cr',                 unit: 'mg/g'          },
    protcr:              { label: 'Prot/Cr',                unit: 'mg/g'          },
    citratocr:           { label: 'Citrato/Cr',             unit: 'mg/mg'         },
    cacitrato:           { label: 'Ca/Citrato',             unit: ''              },
    nak:                 { label: 'Na/K orina',             unit: ''              },
    uricosuria:          { label: 'Uricosuria',             unit: 'mg/1.73m²/día' },
    calciuria:           { label: 'Calciuria',              unit: 'mg/kg/día'     },
    citraturia:          { label: 'Citraturia',             unit: 'mg/kg/día'     },
    fosfaturia:          { label: 'Fosfaturia',             unit: 'mg/kg/día'     },
    oxaluria:            { label: 'Oxaluria',               unit: 'mg/1.73m²/día' },
    magnesuria:          { label: 'Magnesuria',             unit: 'mg/kg/día'     },
    albuminuria:         { label: 'Albuminuria',            unit: 'mg/1.73m²/día' },
    proteinuria:         { label: 'Proteinuria',            unit: 'mg/m²/día'     },
    proteinuriaestimada: { label: 'Proteinuria estimada',   unit: 'mg/m²/día'     },
};

export const SECCIONES = [
    { titulo: 'Datos Generales', keys: ['superficiecorporal','imc'] },
    { titulo: 'Filtrado Glomerular (eGFR) ml/min/1.73m²', keys: ['vpercent','schwartz_neo','schwartz_lact','schwartz_bedside','bokenkamp','ckid_u25_cr','ekfc_cr','ckid_u25_cistc','ekfc_cistc','ckid_u25_combinado'] },
    { titulo: 'Excreción Fraccional', keys: ['efna','efau','efk','efcl'] },
    { titulo: 'Índices Urinarios (Orina Puntual)', keys: ['cacr','mgcr','pcr','rtp','aucr','albcr','oxalatocr','protcr','citratocr','nak','cacitrato'] },
    { titulo: 'Excreción en 24h', keys: ['uricosuria','calciuria','citraturia','fosfaturia','magnesuria','oxaluria','albuminuria','proteinuria','proteinuriaestimada'] },
];
export const TAB_FIELDS = {
    'datos-basicos-tab':  ['fechanacimiento', 'fechaanalitica', 'pesokg', 'tallacm'],
    'bioquimica-tab':     ['ureamgdl', 'creatininaenzmgdl', 'auplasmamgdl', 'naplasmameql',
                           'kplasmameql', 'clplasmameql', 'fosfatasaalcalinaul', 'caplasmamgdl',
                           'pplasmamgdl', 'mgplasmamgdl', 'pthpgml', 'vitaminadngml', 'cistatinacmgl'],
    'gasometria-tab':     ['phplasma', 'pco2mmhg', 'hco3mmoll', 'excesobasesmmoll'],
    'orina-puntual-tab':  ['densidad', 'phorina', 'auorinamgdl', 'naorinameql', 'korinameql',
                           'clorinameql', 'osmolalidadorinamosmkg', 'caorinamgdl', 'fosforoorinamgdl',
                           'magnesioorinamgdl', 'albuminaorinamgdl', 'creatininaorinamgdl',
                           'proteinasorinamgdl', 'citratoorinamgdl', 'oxalatoorinamgdl'],
    'hematologia-tab':    ['hbgl', 'ferritinangml', 'istpercent'],
    'orina-24h-tab':      ['au24hmg', 'ca24hmg', 'p24hmg', 'mg24hmg', 'albumina24hmg',
                           'proteinas24hmg', 'citrato24hmg', 'oxalato24hmg'],
    'ecografia-tab':      ['rinonizquierdomm', 'rinonderechomm']
};